# Get Hotel Search Status [/hotel/v1.0/search/status]
## Get Hotel Search Status [POST]

+ Request getSearchStatus (application/json)
    + Headers
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
    + Attributes (sessionIdReq)

+ Response 200 (application/json)
    + Attributes (getstatusresponse)
