# Get getPayment [api/{version}/payments/{id}]

## Get getPayment [GET]

+ Parameters
    + version:`v1.0` - version number
    + id:`abcd1234` - unique id for payment

+ Request getPaymentRequest (application/json)
    + Headers
      cnx-tenantid: 2ql3bti6juo
      cnx-correlationid: 7e35a975-b76a-4a60-8e93-7aa329a56996
      cnx-stackid: 7e35a975-b76a-4a60-8e93-7aa329a56996
      cnx-environment-token: T1, T2, QA, SG
      cnx-userip: 127.0.0.1
      cnx-unique-requestid: 7e35a975-b76a-4a60-8e93-7aa329a56996
      Content-Type: application/json
      Accept-Language: en-US
      Accept-Encoding: Gzip, deflate
      Accept-Charset: UTF-8
      
+ Response 200 (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationid: 0dc9e51a-fe55-4190-b2c5-8d2405539d47
      cnx-transactionid: 6c4786ee-8afb-46f6-a0c6-89a3ca6b54c3
      Accept-Encoding: gzip, deflate

    + Attributes (getPaymentResponse)
