# Create Order [/hotel/v1.0/order]
## Create Order [POST]
    
+ Request createOrderReq (application/json)

    + Headers
      Content-Type: application/json
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-tenantid: 2ql3bti6juo
      cnx-userip: 127.0.0.1
      Accept-Encoding: gzip, deflate
    
    + Attributes (createOrderRequest)
      
+ Response 200 (application/json)
    + Headers
      Content-Type: application/json
      stackid:07487f70-1c7e-4371-b35e-8ed325dc6d60
      transactionid:70487f70-1c7e-4371-b35e-6ed325dc6d80
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      
    + Attributes (createOrderResponse)
