#  Get Filter Data [/hotel/v1.0/filter-data/{sessionId}]
## Get Filter Data [GET]
+ Parameters
    + sessionId: `0f8fad5b-d9cb-461f-a165-70867728951z` - Unique acknowledgement token that indicates that the request has been received and the processing has been initiated. You must use the session ID returned in the `Initiate Hotel Search` API response for further calls in the same session. The session ID is valid for 60 minutes from the time it is generated.
+ Request filterDataReq (application/json)
    + Headers
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
+ Response 200 (application/json)
    + Attributes (getFilterDataResponse)
