# Map Hotels [/hotel/v1.0/search/results/map]
## Map Hotels [POST]

+ Request mapHotelRequest (application/json)
    + Headers
      cnx-correlationid: hotel-stage-doc-497c-b2e5-2e40b26a9bc2
      cnx-userip: 127.0.0.1
      cnx-tenantid: 2ql3bti6juo
      Accept-Language: en-US
    + Attributes (mapHotelReq)
+ Response 200 (application/json)
    + Attributes (mapHotelResp)
